#!/bin/bash


# laptasus - ASUS laptop tools (backlight, keyboard backlight and etc.)
# la-plugin - keyboard backlight controller
# arguments - {up|down|off}
# Pavel Kulyov <kulyov.pavel@gmail.com>, 2016


# TODO: use lactl config.d to store KEYS_DIR

SUBSYSTEM=kbacl

test-plugin-do () {
	# this directory is a symlink on my machine:
	KEYS_DIR=/sys/class/leds/asus\:\:kbd_backlight

	test -d $KEYS_DIR || exit 0

	MIN=0
	MAX=$(cat $KEYS_DIR/max_brightness)
	VAL=$(cat $KEYS_DIR/brightness)

	if [ "$1" = down ]; then
		VAL=$((VAL-1))
	else
		VAL=$((VAL+1))
	fi

	if [ "$VAL" -lt $MIN ]; then
		VAL=$MIN
	elif [ "$VAL" -gt $MAX ]; then
		VAL=$MAX
	fi

	echo $VAL > $KEYS_DIR/brightness
}

slog () {
	printf "[`date +%d/%m/%Y\ %H:%M:%S`] $SUBSYSTEM: $@\n"
}

plugin-validate-args () {
	slog "got args ($@)"
	[ $# == 1 ] && {
		[ $1 == "up" ] ||
		[ $1 == "down" ] ||
		[ $1 == "off" ]
	} || return 1
	return 0
}

plugin-do () {
	slog "doing $@"
}
