#!/bin/bash


# laptasus - ASUS laptop tools (backlight, keyboard backlight and etc.)
# la-plugin - keyboard backlight controller
# arguments - {up|down|off}
# Pavel Kulyov <kulyov.pavel@gmail.com>, 2016


# TODO: use lactl config.d to store KEYS_DIR

SUBSYSTEM=kbacl

slog () {
	printf "[`date +%d/%m/%Y\ %H:%M:%S`] $SUBSYSTEM: $@\n"
}

plugin-validate-args () {
	slog "got args ($@)"
	[ $# == 1 ] && {
		[ $1 == "up" ] ||
		[ $1 == "down" ] ||
		[ $1 == "off" ]
	} || return 1
	return 0
}

plugin-do () {
	local KEYS_DIR=/sys/class/leds/asus\:\:kbd_backlight

	test -d $KEYS_DIR || exit 0

	local MIN=0
	local MAX=$(cat $KEYS_DIR/max_brightness)
	local VAL=$(cat $KEYS_DIR/brightness)

	case $1 in
		up)
			VAL=$((VAL+1))
			;;
		down)
			VAL=$((VAL-1))
			;;
		off)
			VAL=0
			;;
	esac

	[ $VAL -lt $MIN ] && VAL=$MIN
	[ $VAL -gt $MAX ] && VAL=$MAX

	echo $VAL > $KEYS_DIR/brightness
}
