# laptasus - ASUS laptop tools (backlight, keyboard backlight and etc.)
# Pavel Kulyov <kulyov.pavel@gmail.com>, 2016

PROJ = laptasus
VERSION = 0.1
PACKAGE = $(PROJ)-$(VERSION)

BINDIR  ?= /usr/bin
PREFIX  ?= /etc/$(PROJ)
PLUGDIR ?= $(PREFIX)/plugins

DISTFILES = \
	LICENSE   \
	Makefile  \
	README.md

PLUGINFILES = $(shell find $(PROJ)/plugins -name "la-*")

define conf
	echo "$1" >> $(PROJ)/config
endef

gen-config: clean
	@echo "Generating default $(PROJ) configuration."
	@$(call conf,# laptasus - ASUS laptop tools.)
	@$(call conf,# Pavel Kulyov <kulyov.pavel@gmail.com>, 2016)
	@$(call conf,# This configuration file was autogenerated.)
	@$(call conf,# Feel free to add here key=value pairs for custom la-plugins.)
	@$(call conf,PLUGDIR=$(PLUGDIR))

dist: clean
	@echo "Creating dist tarball:"
	@mkdir -pv $(PACKAGE)
	@cp -av $(DISTFILES) $(PACKAGE)
	@tar -cvf $(PACKAGE).tar $(PACKAGE)
	@gzip -fv $(PACKAGE).tar
	@rm -rfv $(PACKAGE)
	@echo "Dist tarball '$(PACKAGE).tar' created."

install: gen-config
	@echo "Installing $(PACKAGE):"
	@echo "Binary: $(BINDIR)"
	@echo "Prefix: $(PREFIX)"
	@mkdir -pv $(BINDIR) $(PLUGDIR)
	@cp -uv $(PROJ)/lactl $(BINDIR)
	@cp -uv $(PROJ)/config $(PREFIX)
	@cp -uRv $(PLUGINFILES) $(PLUGDIR)

uninstall:
	@echo "Uninstalling $(PACKAGE):"
	@rm -rfv $(PREFIX) $(BINDIR)/lactl
	@echo "$(PACKAGE) uninstalled."

clean:
	@rm -rfv $(PACKAGE) $(PROJ)/config

.PHONY: dist install uninstall clean
