#!/bin/sh


PROG=$0

usage () {
    printf "$PROG\n";
}

exit_usage() {
    usage;
    exit $1;
}


[ $# -gt 0 ] && [ $# -lt 4 ] || exit_usage ;

ACTION=$1
VALUE=$2


split-left () {
    echo $1 | awk 'BEGIN{FS=$2} {print $1}'
}


discover-and-load () {
    printf "$@\n"
    . ~/proj/laptasus/laptasus/plugins/la-keyboard-backlight
    return 0
}


start () {
    printf "in start\n"

    pipe=/tmp/msgpipe
    trap "rm -f $pipe" EXIT
    if [[ ! -p $pipe ]]; then
        mkfifo $pipe
    fi



    while true
    do
        if read line <$pipe; then
            if [[ "$line" == quit ]]; then
                break
            else
                SUBSYSTEM=$(echo $line | awk 'BEGIN{FS="::"} {print $1}')
                ARGS=$(echo $line | awk 'BEGIN{FS="::"} {print $2}')

                discover-and-load $SUBSYSTEM
                [ $? -gt 0 ] && continue
                plugin-validate-args $ARGS
                plugin-do $ARGS


            fi
        fi
    done
}

stop () {
    printf "in stop\n"
}

unhandled () {
    printf "unhandled\n"
}


case $ACTION in
    start)
        printf "Starting...\n";
        start;
        ;;
    stop)
        printf "Stopping...\n";
        stop;
        ;;
    *)
        printf "Not responded action.\n";
        unhandled;
        ;;
esac
