#!/bin/bash


# laptasus - ASUS laptop tools (backlight, keyboard backlight and etc.)
# Pavel Kulyov <kulyov.pavel@gmail.com>, 2016

# TODO: parse and pass args to plugin
# TODO: implement safe discover-and-load function to load plugin


PROG="${0##*/}"
PLUGDIR=/home/most/proj/laptasus/laptasus/plugins

usage () {
    cat << EOF

Usage: $PROG {start|stop}
ASUS laptop tools daemon.
Dispatches requests from pipe to appropriate plugin (handler).

Arguments:
    -h, --help    print this help message
    start         start the daemon
    stop          stop the daemon

Exit statuses:
    0 if Ok,
    1 if serious trouble.
EOF

    [ ! -z "$1" ] && exit $1 || exit 0
}

[ $# == 1 ] || usage 1
[ $1 == "-h" ] || [ $1 == "--help" ] && usage

log () {
    printf "[`date +%d/%m/%Y\ %H:%M:%S`] $PROG: $@\n"
}

discover-and-load () {
    log $@
    . $PLUGDIR/la-keyboard-backlight
    return 0
}

start () {
    pipe=/tmp/msgpipe
    trap "rm -f $pipe" EXIT
    if [[ ! -p $pipe ]]; then
        mkfifo -m 0422 $pipe
    fi

    while true
    do
        if read line <$pipe; then
            if [[ "$line" == quit ]]; then
                break
            else
                SUBSYSTEM=$(echo $line | awk 'BEGIN{FS="::"} {print $1}')
                ARGS=$(echo $line | awk 'BEGIN{FS="::"} {print $2}')

                discover-and-load $SUBSYSTEM
                [ $? -gt 0 ] && continue
                plugin-validate-args $ARGS
                [ $? == 0 ] && plugin-do $ARGS


            fi
        fi
    done
}

stop () {
    return 0
}

unhandled () {
    log "Caught request to unknown substystem: $SUBSYSTEM"
    log "args: $ARGS"
}

case $1 in
    start)
        printf "Starting...\n"
        start
        ;;
    stop)
        printf "Stopping...\n"
        stop
        ;;
    *)
        unhandled
        ;;
esac
