#!/bin/bash

# laptasus - ASUS laptop tools (backlight, keyboard backlight and etc.)
# Pavel Kulyov <kulyov.pavel@gmail.com>, 2016

# TODO: parse and pass args to plugin
# TODO: implement safe discover-and-load function to load plugin
# TODO: move out pipe path to config
# TODO: use /tmp to parse config for the basic eval safety

PROG="${0##*/}"


# Redefines by config
PIPE=/tmp/lapipe
PLUGDIR=/home/most/tmp/etc/laptasus/plugins

CONF_GLOBAL=/etc/laptasus/config
CONF_LOCAL=../etc/laptasus/config

[ -f $CONF_GLOBAL ] && . $CONF_GLOBAL || {
        [ -f $CONF_LOCAL ] && . $CONF_LOCAL
        } || echo "No configuration file found."

PLUGINS=($PLUGDIR/la-*)

log() {
    printf "[`date +%d/%m/%Y\ %H:%M:%S`] $PROG: $@\n"
}

unhandled() {
    log "Caught request to unknown substystem: $SUBSYSTEM"
    log "args: $ARGS"
}

discover-and-load() {
    log $@
    for plugin in "${PLUGINS[@]}";
    do
        [ $SUBSYSTEM == $1 ] && . $plugin && return 0
    done

    return 1
}

loop() {
    trap "rm -f $PIPE" EXIT
    if [[ -p $PIPE ]]; then
        log "Looks like another instance of $PROG is working."
        exit 1
    else
        mkfifo -m 0422 $PIPE
    fi

    while true
    do
        if read line <$PIPE; then
            [ "$line" == "lactl::quit" ] && break

            SUBSYSTEM=$(echo $line | awk 'BEGIN{FS="::"} {print $1}')
            ARGS=$(echo $line | awk 'BEGIN{FS="::"} {print $2}')

            discover-and-load $SUBSYSTEM
            [ $? -gt 0 ] && continue
            plugin-validate-args $ARGS
            [ $? == 0 ] && plugin-do $ARGS
        fi
    done
}

case $1 in
    start)
        loop
        ;;
    stop)
        [ -p $PIPE ] && echo "lactl::quit" > $PIPE
        exit 0
        ;;
    *)
        log "Unknown action $1"
        exit 1
        ;;
esac
